### ISSUE TITLE
Sincronización horaria

### ISSUE THREAD

**Issue by despiojo** [DesarrolloSinapse/control_presencia#4]
El equipo lector, debería sincronizar hora, con un proveedor externo de tiempo, bien pudiera ser el propio servidor que corre los scripts.

**Comment by DesarrolloSinapse** [comment]
Para dar solución a esta issue vamos a aprovechar en el codigo starting.py que se ha subido dentro de la carpeta cliente y vamos a configurar una llamada cada X horas a un servidor ntp usando un scheduler y el modulo ntplib de python. Esto se hará creando un thread paralelo que esté permanentemente en ejecución y en segundo plano.

**Comment by despiojo** [comment]
Ok, lo substituyo en la lectora pues y la doy por cerrada cuando lo pruebe

**Comment by DesarrolloSinapse** [comment]
Se ha optado por añadir un script de linux que simplifica todo el procedimiento que se menciona antes, así como un fichero de texto en el que se explica los pasos a seguir para que el funcionamiento sea el óptimo.

**Comment by despiojo** [comment]
Porque lo has cambiado?

**Comment by DesarrolloSinapse** [comment]
Se ha cambiado porque es una manera más simple y eficiente de hacer lo mismo que se pretendía.
